// client/src/app/components/login-form/login-form.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-login-form',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './login-form.component.html',
})
export class LoginFormComponent {

}

<div
	class="bg-gray-100 pt-5 flex flex-col content-center gap-5 lg:rounded-md h-screen justify-center overflow-hidden lg:grid lg:grid-cols-2"
>
	<div class="lg:border lg:border-violet-500 lg:rounded-md">
		<h1 class="text-4xl font-bold font-primary text-center">
			Berry<span class="text-[#81809F]">Exams</span>
		</h1>
		<h2 class="text-center italic">
			Sign <span class="text-[#81809F]">In</span>
		</h2>
		<form class="px-4 flex flex-col gap-2 content-center">
			<div class="flex flex-col py-4">
				<label class="text-lg font-semibold" for="userName"
					><fa-icon
						class="text-sm text-purple"
						[icon]="faEnvelope"
					></fa-icon>
					Email:</label
				>
				<input
					class="border outline-none border-gray-200 px-2 py-2 focus:border focus:border-purple transition-all ease-in-out duration-300 rounded-md"
					type="text"
					name="userName"
					#userName
					placeholder="jhondoe@email.com"
					required
					onchange="hadleInput(userName.value)"
				/>
			</div>
			<div class="flex flex-col py-4">
				<label class="text-lg font-semibold" for="password"
					><fa-icon
						class="text-sm text-purple"
						[icon]="faLock"
					></fa-icon>
					Password:</label
				>
				<input
					class="border outline-none border-gray-200 px-2 py-2 focus:border focus:border-purple transition-all ease-in-out duration-300 rounded-md"
					type="password"
					name="password"
					id="password"
					placeholder="********"
				/>
			</div>
			<button
				class="text-sm text-cyan-600 hover:cursor-pointer"
				(click)="toggle.emit()"
				type="button"
			>
				You don't have an account?
			</button>

			<button
				class="btn bg-blue w-36 text-center px-4 py-1 mx-auto"
				(click)="login($event)"
			>
				Log In
			</button>
		</form>
	</div>
	<img class="h-96" src="/assets/images/form_image.png" alt="login image" />
</div>

// client/src/components/auth/LoginForm.tsx
interface formProps {
    state: string;
    setState: () => void;
}

const LoginForm = ({ setState }: formProps) => {
    return (
        <div className="transition-opacity ease-in-out opacity-100">
            <form className="mb-4">
                <div className="flex flex-col mb-4">
                    <label
                        htmlFor="email"
                        className=" text-purple text-md font-semibold mb-2"
                    >
                        <span>Email </span>
                    </label>
                    <input
                        className="oshadow appearance-none border-b-2 shadow-md w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:border-purple transition-[border,colors] duration-500"
                        type="email"
                        placeholder="jhondoe@email.com"
                        required
                    />
                </div>
                <div className="flex flex-col mb-4">
                    <label
                        htmlFor="password"
                        className=" text-purple text-md font-semibold mb-2"
                    >
                        <span>Password </span>
                    </label>
                    <input
                        className="oshadow appearance-none border-b-2 shadow-md w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline focus:border-purple transition-[border,colors] duration-500"
                        type="password"
                        placeholder="*******"
                        required
                    />
                </div>
                <button
                    type="button"
                    className="bg-black text-white px-2 py-1 mx-auto block w-36 transition-colors hover:bg-violet-400 hover:text-black duration-500"
                >
                    Log in
                </button>
            </form>
            <button className="cursor-pointer text-blue-600" onClick={setState}>
                You don't have an account?
            </button>
        </div>
    );
};

export default LoginForm;
