// client/src/pages/LandingPage.tsx
import { Link } from "react-router-dom";
import { FaBook, FaSchool } from "react-icons/fa6";
const LandingPage = () => {
    const logged = false;
    const services = [
        {
            title: "General Exams",
            content:
                "You have access to ONE general exam, you want to make your way into the UNAM or some school? then make a general exam an practice",
            icon: <FaSchool />,
        },
        {
            title: "Topic Exams",
            content:
                "You have access to 3 general exams to improve your knowledge, you had problems with history? then make a history exam!",
            icon: <FaBook />,
        },
    ];
    return (
        <main className="md:mx-auto gap-5 flex flex-col">
            <div className="flex flex-col items-center my-5">
                <h1 className="mx-auto text-4xl font-bold text-center">
                    Welcome to <span className="b">Berry Exams</span>
                </h1>
                <span className="text-center mx-auto italic">
                    if you think you know, you don't
                </span>
            </div>
            <div className="max-w-5xl md:mx-auto gap-5 grid md:grid-cols-2 place-items-center m-4 mx-auto p-3">
                <h1 className="text-4xl font-bold max-w-max mx-auto self-end">
                    Want to improve your knowledge?
                </h1>
                <div className="md:row-span-2 w-56 md:w-96">
                    <img src="/study.png" alt="study icon" />
                </div>

                <div className="flex flex-col gap-4">
                    <p>Check our plans and make exams to be better</p>
                    <Link
                        to={logged ? "/exams" : "/auth"}
                        className="flex justify-center items-center gap-x-2 bg-black text-white py-3 px-[1.1rem] transition-colors duration-500 hover:bg-purple text-xl mx-auto max-w-80"
                    >
                        <FaBook />
                        Start a new Exam
                    </Link>
                </div>
            </div>

            <section className="p-3 bg-[#D4D4D4]">
                <div className="max-w-6xl mb-5 p-3 grid gap-5 mx-auto">
                    <h2 className="relative text-4xl font-bold max-w-max mx-auto mt-3 after:content-[''] after:bg-purple after:absolute after:block after:w-10 after:h-7 after:-top-1 after:-right-2 md:self-end">
                        Services.
                    </h2>
                    <div className="max-w-6xl mb-5 p-8 grid gap-5 justify-center gap-y-8 pt-4 md:grid-cols-2">
                        {services.map((service, i) => (
                            <article className="relative group/card" key={i}>
                                <div className="absolute w-full h-full border-4 border-purple top-0 left-0 transition-transform duration-500 group-hover/card:translate-x-3 group-hover/card:translate-y-3"></div>

                                <div className="h-full bg-body border-4 border-black pt-24 px-4 pb-12 z-[4] relative transition-[colors, border] duration-500">
                                    <div className="relative inline-block">
                                        <div className="absolute w-6 h-6 bg-purple -right-[2px] -top-[2px]"></div>
                                        <p className="text-3xl text-black relative z-[5]">
                                            {service.icon}
                                        </p>
                                    </div>
                                    <h2 className="text-2xl font-bold mb-5">
                                        {service.title}.
                                    </h2>
                                    <p>{service.content}.</p>
                                </div>
                            </article>
                        ))}
                    </div>
                </div>
            </section>
        </main>
    );
};

export default LandingPage;

// client/src/app/pages/landing-page/landing-page.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FooterComponent } from '../../components/footer/footer.component';
import { faQuestion, faCircleInfo } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';
import { RouterLink, RouterLinkActive } from '@angular/router';

@Component({
	selector: 'app-landing-page',
	standalone: true,
	imports: [
		CommonModule,
		FooterComponent,
		FontAwesomeModule,
		RouterLink,
		RouterLinkActive,
	],
	templateUrl: './landing-page.component.html',
})
export class LandingPageComponent {
	faQuestion = faCircleInfo;
	screenWidht = window.innerWidth;
}

<header
	class="flex flex-row gap-4 items-center px-1 py-4 justify-evenly border-b border-b-gray-200 sticky top-0 bg-white"
>
	<h1 class="text-4xl font-bold font-primary">
		Berry<span class="text-[#81809F]">Exams</span>
	</h1>
	<a
		routerLink="/auth"
		routerLinkActive="active"
		ariaCurrentWhenActive="page"
		class="btn bg-blue hover:bg-lightPink px-4 py-2 text-center font-second lg:w-32"
		>Log in</a
	>
</header>
<main class="flex flex-col gap-4 content-center">
	<div
		class="flex flex-col gap-4 lg:flex-row content-center bg-emerald-100 lg:items-center lg:max-w-4xl lg:mx-auto"
	>
		<div class="flex flex-col gap-4 mt-2 content-center px-4 py-2">
			<h2 class="text-xl font-bold text-center">
				Reinforce your knowledge
			</h2>
			<p>A great way to reinforce your knowledge in general topics</p>
			<p>Improve yourself with some exams</p>
			<a
				routerLink="/auth"
				ariaCurrentWhenActive="page"
				ariaCurrentWhenActive="page"
				class="btn px-4 py-2 w-44 mx-auto bg-lightPurple hover:bg-blue text-center font-second"
				>Register Now</a
			>
		</div>
		@if(screenWidht <= 560) {
		<img
			class="h-3/4 w-full"
			src="/assets/images/study_large.jpg"
			alt="study image"
		/>
		} @else {
		<img class="w-1/2" src="/assets/images/study.jpg" alt="study image" />
		}
	</div>
	<div class="flex flex-col gapx-4 content-center">
		<h2 class="text-4xl font-bold text-center mb-4">Our services</h2>
		<div class="lg:grid lg:grid-cols-3">
			<article
				class="p-3 flex flex-col gap-4 text-center content-center bg-blue"
			>
				<img
					class="w-24 mx-auto"
					src="/assets/images/icono_estudio.png"
					alt="icono estudio"
				/>
				<h2 class="text-xl font-bold text-center mb-4">
					What can you do here?
				</h2>
				<p>
					Here you gonna be able to make exams in different topics or
					make one
					<span class="font-bold">admition like exam</span> to
					practice or reinforce the knowledge you already had.
				</p>
			</article>
			<article class="p-3 bg-emerald-100 text-center">
				<img
					class="w-24 mx-auto"
					src="/assets/images/icono_estudio.png"
					alt="icono estudio"
				/>
				<h2 class="text-xl font-bold text-center mb-4">
					Can I make unlimited exams?
				</h2>
				<p>
					Sorry but no, you have access to 1 general exam and 3 topic
					exams (the topic are whatever you want).
				</p>
			</article>

			<article class="p-3 bg-amber-100 text-center">
				<img
					class="w-24 mx-auto"
					src="/assets/images/icono_estudio.png"
					alt="icono estudio"
				/>
				<h2 class="text-xl font-bold text-center mb-4">
					What topics can i have exams?
				</h2>
				<p>
					We offer exams of global history, math, chemestry, biology,
					Spanish, Pshisycal, literatury, Geografy, Mexican Hisotry.
				</p>
			</article>
		</div>
	</div>
	<div class="flex flex-col gapx-4 content-center">
		<h2 class="text-2xl font-bold text-center mb-3">FAQS</h2>
		<div
			class="lg:max-w-xl lg:mx-auto mb-5 flex flex-col gap-4 text-center"
		>
			<article class="border border-gray-200">
				<h3
					class="py-3 bg-gray-200 text-center font-bold text-xl mb-2 relative"
				>
					Why Berry Exams?
				</h3>
				<p class="p-4">
					Well the response is simple, i want to improve my skills in
					programming so i build this site, the idea come from my best
					friend and i make the magic
				</p>
			</article>
			<article class="border border-gray-200">
				<h3
					class="py-3 bg-gray-200 items-center text-center font-bold text-xl mb-2 relative"
				>
					I need a real account?
				</h3>

				<p class="p-4">
					Obviuosly *wing wing*... being honest this is just to
					improve my skill so if you don't wanna expose your data then
					you can create a fake account and used the app
				</p>
			</article>
			<article class="border border-gray-200">
				<h3
					class="py-3 bg-gray-200 text-center font-bold text-xl mb-2 relative"
				>
					Where do you get the questions for the exams?
				</h3>

				<p class="p-4">Well that's a secret 👀</p>
			</article>
		</div>
	</div>
</main>
<app-footer />
