// client/src/app/components/footer/footer.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { faHome } from '@fortawesome/free-solid-svg-icons';
import { FontAwesomeModule } from '@fortawesome/angular-fontawesome';

@Component({
	selector: 'app-footer',
	standalone: true,
	imports: [CommonModule, FontAwesomeModule],
	templateUrl: './footer.component.html',
})
export class FooterComponent {
	faHomme = faHome;

	links = [
		{
			href: 'https://github.com/ArmandoAlmanza/',
			icon: '/assets/icons/github.svg',
			alt: "github icon"
		},
		{
			href: 'https://www.linkedin.com/in/armando-almanza/',
			icon: '/assets/icons/linkedin.svg',
			alt: "linkedin icon"
		},
		{
			href: 'https://www.instagram.com/arandano_triston/',
			icon: '/assets/icons/instagram.svg',
			alt: "instagram icon"
		},
	];
}

<footer class="bg-[#606060] p-4 flex flex-col gap-3 text-white">
	<div>
		<h3 class="text-xl text-center"><span class="font-bold">Created By: </span>Armando Almanza</h3>
		<!-- <nav>
			<h4>My links</h4>
			<div class="flex flex-row gap-4 justify-evenly p-2">
				@for (link of links; track $index) {
				<a href="{{ link.href }}" target="_blank"
					><img
						class="h-4"
						src="{{ link.icon }}"
						alt="{{ link.alt }}"
				/></a>
				}
			</div>
		</nav> -->
	</div>
</footer>

// client/src/components/Footer.tsx
import { FaGithub, FaInstagram, FaX } from "react-icons/fa6";

const Footer = () => {
    return (
        <footer className="flex flex-col p-4 gap-5">
            <div className="flex flex-col content-center items-center gap-3">
                <h2 className="text-xl">
                    Made by{" "}
                    <span className="text-xl font-semibold">
                        Armando<span className="text-purple-300">Almanza</span>
                    </span>
                </h2>
                <nav className="flex flex-row justify-between gap-3">
                    <a
                        className="text-xl transition-colors hover:text-purple duration-300"
                        href="https://github.com/ArmandoAlmanza"
                        target="_blank"
                    >
                        <FaGithub />
                    </a>
                    <a
                        className="text-xl transition-colors hover:text-purple duration-300"
                        href="https://github.com/ArmandoAlmanza"
                        target="_blank"
                    >
                        <FaInstagram />
                    </a>
                    <a
                        className="text-xl transition-colors hover:text-purple duration-300"
                        href="https://github.com/ArmandoAlmanza"
                        target="_blank"
                    >
                        <FaX />
                    </a>
                </nav>
            </div>
        </footer>
    );
};

export default Footer;
